# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-us
  languageName: English
  weight: 1

es:
  locale: es-es
  languageName: Español
  weight: 2

