# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /bio/
    weight: 10
  - name: Services
    url: /services/
    weight: 20
  - name: Portfolio
    url: /projects/
    weight: 30
  - name: Research
    url: /research/
    weight: 40
  - name: Workshops
    url: /courses/
    weight: 50
  - name: Insights
    url: /news/
    weight: 60
  - name: Resources
    url: /resources/
    weight: 70
  - name: Contact
    url: /contact/
    weight: 100
